#!/usr/bin/env python3

import argparse
import json
import logging
import os
import shlex
import subprocess
from functools import lru_cache

from typing import Any, Dict, Iterator, List, Optional, Set, Union, cast

SCRIPT_NAME = "drbd-resync"
DRBD_CMD_STATUS = "drbdsetup status all --json"
DRBD_CMD_VERIFY = "drbdadm verify {resource_name}:{peer}/0"
DRBD_CMD_WAIT_SYNC = "drbdadm wait-sync {resource_name}"
DRBD_CMD_INVALIDATE = "drbdadm invalidate {resource_name}:{peer}/0 --reset-bitmap=no"
DRBD_CMD_INVALIDATE_REMOTE = (
    "drbdadm invalidate-remote {resource_name}:{peer}/0 --reset-bitmap=no"
)

logger = logging.getLogger(__name__)


def run_command(cmd: str, ignore_dry_run: bool = False, remote_host: str = "") -> str:
    if remote_host:
        cmd = f"ssh root@{remote_host} -C {cmd}"
    logger.debug(cmd)
    if DRY_RUN and not ignore_dry_run:
        return ""
    try:
        return subprocess.run(
            shlex.split(cmd),
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
        ).stdout.strip()
    except subprocess.CalledProcessError as e:
        logger.error("%s failed with error code %d: `%s`", cmd, e.returncode, e.output)
        raise e


def run_write_command(cmd: str, remote_host: str = "") -> str:
    return run_command(cmd, ignore_dry_run=False, remote_host=remote_host)


def run_read_command(cmd: str, remote_host: str = "") -> str:
    return run_command(cmd, ignore_dry_run=True, remote_host=remote_host)


# FIXME Change to @cache when upgrading to python>=3.9
@lru_cache()
def get_hostname(ip: str) -> str:
    return run_read_command("hostname", remote_host=ip)


class Host:
    def __init__(self, ip: str):
        self.ip = ip

    @property
    def hostname(self) -> str:
        return get_hostname(self.ip)

    def __str__(self) -> str:
        return ",".join([self.hostname, self.ip])

    def __eq__(self, other: Any) -> bool:
        return (
            isinstance(other, Host)
            and self.hostname == other.hostname
        )

    def __hash__(self) -> int:
        return hash(self.hostname)

    def to_json(self) -> Dict[str, Any]:
        return self.__dict__

class LinstorPeer(Host):
    def __init__(self, ip: str, from_ip: str):
        super().__init__(ip)
        self.from_host = Host(from_ip)

    def __str__(self) -> str:
        return ",".join([super().__str__(), str(self.from_host)])

    # Intentionally not overloading eq and hash since the from_host
    #  does not change the peer

class ResourceKey:
    """Represents the identifying pair of a resource's name and peer hostname.

    Attributes:
        name (str): The resource's name.
        peer (LinstorPeer): The peer on which the resource instance resides.
    """

    def __init__(self, name: str, peer: LinstorPeer):
        self.name = name
        self.peer = peer

    def __str__(self) -> str:
        return f"{self.name}:{self.peer}"

    def __eq__(self, other):
        return (
            isinstance(other, ResourceKey)
            and self.name == other.name
            and self.peer == other.peer
        )

    def __hash__(self) -> int:
        return hash((self.name, self.peer))

    def to_json(self) -> Dict[str, Any]:
        return self.__dict__


class ResourceStatus(ResourceKey):
    """Represents a resource along with its synchronization status.

    Extends:
        ResourceKey

    Attributes:
        out_of_sync (int): Amount of data out of sync, in kilobytes (KB).
            This value represents the replication lag between the different nodes.
            It is gathered from LINSTOR's reported 'out-of-sync' metric.

    Properties:
        key (str): A string representation of the resource key (``name:peer``).
    """

    def __init__(self, name: str, peer: LinstorPeer, out_of_sync: int):
        super().__init__(name, peer)
        self.out_of_sync = out_of_sync

    @property
    def key(self) -> str:
        return super().__str__()

    def __str__(self) -> str:
        return f"{self.key},{self.out_of_sync}"

    def to_json(self) -> Dict[str, Any]:
        return self.__dict__


JSON = Dict[str, Any]
StatusUnion = Union[List[ResourceStatus], Iterator[ResourceStatus]]


def get_peer_from_connection(connection: JSON) -> Optional[LinstorPeer]:
    for path in connection.get("paths", []):
        if path.get("established"):
            remote = path.get("remote_host", {}).get("address")
            local = path.get("this_host", {}).get("address")
            if remote and local:
                return LinstorPeer(remote, local)
    return None


def get_bad_resources_from_status(
    status: List[JSON],
    oos_only: bool = False,
    resource_name: str = "",
) -> StatusUnion:
    return (
        ResourceStatus(
            name=resource.get("name", ""),
            peer=cast(LinstorPeer, get_peer_from_connection(connection)),
            out_of_sync=peer_device.get("out-of-sync", 0),
        )
        for resource in status
        for connection in resource.get("connections", [])
        for peer_device in connection.get("peer_devices", [])
        if (
            (not oos_only or peer_device.get("out-of-sync", 0) > 0)
            and (not resource_name or resource.get("name", "") == resource_name)
            and get_peer_from_connection(connection)
        )
    )


def get_peers_from_status(status: List[JSON]) -> Set[LinstorPeer]:
    peers = set()
    for resource in status:
        for connection in resource.get("connections", []):
            peer = get_peer_from_connection(connection)
            if peer:
                peers.add(peer)
    return peers


def get_status(remote_host: str = "") -> List[JSON]:
    return json.loads(
        run_read_command(DRBD_CMD_STATUS, remote_host=remote_host)
    )


def get_oos_statuses(
    oos_only: bool = False,
    resource_name: str = "",
    remote_host: str = "",
) -> StatusUnion:
    return get_bad_resources_from_status(
        get_status(remote_host),
        oos_only=oos_only,
        resource_name=resource_name,
    )


def drbd_verify_resource(resource: ResourceStatus, remote_host: str = "") -> None:
    run_write_command(
        DRBD_CMD_VERIFY.format(resource_name=resource.name, peer=resource.peer.hostname),
        remote_host=remote_host,
    )
    run_read_command(
        DRBD_CMD_WAIT_SYNC.format(resource_name=resource.name),
        remote_host=remote_host,
    )


def drbd_resync_resource(
    resource: ResourceStatus, local: bool = False, remote_host: str = ""
) -> None:
    cmd = DRBD_CMD_INVALIDATE if local else DRBD_CMD_INVALIDATE_REMOTE
    run_write_command(
        cmd.format(resource_name=resource.name, peer=resource.peer.hostname),
        remote_host=remote_host,
    )
    run_read_command(
        DRBD_CMD_WAIT_SYNC.format(resource_name=resource.name),
        remote_host=remote_host,
    )


def get_all_peers() -> Set[LinstorPeer]:
    hosts = get_peers_from_status(get_status())
    local_ip = next(iter(hosts)).from_host.ip
    hosts.add(LinstorPeer(local_ip, local_ip))
    return hosts


def main(
    resource_name: str = "",
    print_report: bool = False,
    verify_only: bool = False
) -> None:
    hosts = get_all_peers()
    all_resources: Dict[str, List[ResourceStatus]] = {}
    reports: List[ResourceStatus] = []
    for host in hosts:
        remote_host = host.ip if host.ip != host.from_host.ip else ""

        for status in list(get_oos_statuses(resource_name=resource_name, remote_host=remote_host)):
            drbd_verify_resource(status, remote_host=remote_host)

        resources = get_oos_statuses(oos_only=True, resource_name=resource_name, remote_host=remote_host)

        for resource in resources:
            logging.info(
                "resource `%s` on `%s` is out of sync by %s",
                resource.name, resource.peer.hostname, resource.out_of_sync
            )
            all_resources.setdefault(resource.name, []).append(resource)

    for resource_name, resources in all_resources.items():
        msg = f"{resource_name} is reported out-of-sync by:"
        counts: Dict[ResourceStatus, int] = {}
        for resource in resources:
            counts[resource] = counts.get(resource, 0) + 1
            msg += "\n\t{} on {} by {}".format(
                resource.peer.from_host.hostname, resource.peer.hostname, resource.out_of_sync
            )
        logger.info(msg)

        max_count = max(counts.values())
        top_resources = [s for s, c in counts.items() if c == max_count]

        # Each host will check which peer's resource has different values,
        #  admitting 2 hosts with a sane resource and 1 with corrupted data:
        #  The corrupted one will report each as out-of-sync,
        #  while the sane ones will report the corrupted one as out-of-sync;
        #  this will result in 2 reports for the corrupted one
        #  and one report for each sane host. We can infer from this that the one with
        #  the most reports is the corrupted one.
        #  In the event of a tie, it's safer to leave it to human decision
        #  since which is which can't be inferred.
        if len(top_resources) > 1:
            logger.error(
                "Tie detected: multiple hosts with highest reports (%d): %s. Skipping.",
                max_count,
                ", ".join([s.peer.hostname for s in top_resources]),
            )
            continue

        top_resource = top_resources[0]
        logger.info(
            "Designed %s as the host with the corrupted %s",
            top_resource.peer.hostname, top_resource.name
        )
        reports.append(top_resource)

        if verify_only:
            continue

        drbd_resync_resource(top_resource, remote_host=top_resource.peer.from_host.ip)

    if print_report:
        print(json.dumps(reports, default=lambda o: o.to_json()))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verify-only", action="store_true")
    parser.add_argument("--print", action="store_true")
    parser.add_argument("--resource", type=str)
    parser.add_argument(
        "--log-level",
        type=lambda x: x.upper(),
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        default="INFO",
    )

    args = parser.parse_args()
    DRY_RUN = args.dry_run

    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), None),
        format=f"%(asctime)s {SCRIPT_NAME}: [{os.getpid()}] %(levelname)-8s %(message)s",
        datefmt="%b %e %H:%M:%S"
    )
    main(
        resource_name=args.resource,
        print_report=args.print,
        verify_only=args.verify_only
    )
